---
service: aws-lambda-edge

frameworkVersion: "^1.33.1"

plugins:
  - serverless-finch
  - serverless-plugin-cloudfront-lambda-edge

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'test'}

functions:
  app:
    handler: handlers.app
    environment:
      VERSION: 0.0.0
      NODE_ENV: production
      CDN: https://s3-${self:provider.region}.amazonaws.com/${self:custom.client.bucketName}

custom:
  name: aws-lambda-edge
  domain: immutableweb.app
  domainName: ${self:provider.stage}.${self:custom.name}.${self:custom.domain}
  cdnName: cdn.${self:custom.name}.${self:custom.domain}
  client:
    bucketName: immutablewebapps-${self:service}
    distributionFolder: .bucket

package:
  exclude:
    - "*/**"
  include:
    - "handlers/*.js"
